name: lint
on:
  pull_request:
    branches:
    - cao
  push:
    
jobs:
  lint-moudle:
    name: lint
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-versions: 1.17
      - run: go version
          
      - name: output files
        run: echo $PWD
          
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: /home/runner/work/go-github-actions/go-github-actions
          skip-pkg-cache: true
          
        
  
